name: orbyt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase Core - obrigatório
  firebase_core: ^2.30.0
  
  # Firebase Auth - login/cadastro
  firebase_auth: ^4.18.0
  
  # Firestore - banco de dados
  cloud_firestore: ^4.17.0
  
  file_selector: ^1.0.3
  
  intl: ^0.19.0
  http: ^1.1.0
  
  
  
  # UI bonita (opcional)
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/orby.png
    - assets/images/ob2.png
    - assets/images/ob3.png
    - assets/images/ob5.png
    - assets/images/orby_semtxt.png
    - assets/images/orby_base1.png
    - assets/images/orby_base2.png
    - assets/images/orby_base3.png
    - assets/images/orby_base4.png
    - assets/images/orby_base5.png
    - assets/images/orby_base6.png
    - assets/images/orby_base7.png
    - assets/images/orby_base8.png
    - assets/images/orby_base9.png
  
  
